# DATABASE
db.url=jdbc:postgresql://localhost:5432/qr_reconciliation_db
db.username=admin
db.password=admin123
db.pool.size=10

# SFTP CLIENT (kết nối vào SFTP server)
sftp.host=localhost
sftp.port=2222
sftp.username=sftpuser
sftp.password=sftppass
sftp.remote.path=/

# SFTP SERVER LOCAL (giả lập đối tác để test)
sftp.server.port=2222
sftp.server.host.key.path=sftp_host_key
sftp.server.upload.dir=sftp-data/upload

# EMAIL
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.username=hoanglamdung13092005@gmail.com
mail.password=gkzryumkvoicsciu
mail.from=hoanglamdung13092005@gmail.com
mail.to=23520330@gm.uit.edu.vn